const PROJECTS = [
	{
		title: "Amigos",
		slug: "amigos",
		type: "قسم الابتكار",
		thumbnail: "https://i.ibb.co/BrLxPbs/amigos-thumbnail.jpg",
		slides: [
			"https://i.ibb.co/YfmzGts/amigos-slide-1.jpg",
			"https://i.ibb.co/pKkLtV1/amigos-slide-2.jpg",
			"https://i.ibb.co/XyH54cC/amigos-slide-3.jpg",
			"https://i.ibb.co/k19Z5Kd/amigos-slide-4.jpg",
			"https://i.ibb.co/yyBtY0N/amigos-slide-5.jpg",
			"https://i.ibb.co/3431F4m/amigos-slide-6.jpg",
			"https://i.ibb.co/L03CFpX/amigos-slide-7.jpg",
			"https://i.ibb.co/VmvmrKj/amigos-slide-8.jpg",
			"https://i.ibb.co/mG1rFCZ/amigos-slide-9.jpg",
		],
		description: "لقد صممنا مفهوم الشعار والشعار وملصق العبوة.",
	},
	{
		title: "Atlas",
		slug: "atlas",
		type: "التصميم الداخلي والعمارة",
		thumbnail: "https://i.ibb.co/KrT4PMh/atlas-thumbnail.jpg",
		slides: [
			"https://i.ibb.co/MR1fjYj/atlas-slide-1.jpg",
			"https://i.ibb.co/7Y0K53Z/atlas-slide-2.jpg",
			"https://i.ibb.co/CQ6xTL3/atlas-slide-3.jpg",
			"https://i.ibb.co/sqMJLPh/atlas-slide-4.jpg",
			"https://i.ibb.co/dfnLCqY/atlas-slide-5.jpg",
			"https://i.ibb.co/f1RdFV8/atlas-slide-6.jpg",
			"https://i.ibb.co/YRnNYPM/atlas-slide-7.jpg",
		],
		description: "قمنا بتجديد المكان (داخلي / خارجي) أثناء إعادة تصميم الشعار وتصميم بطاقات العمل والنشرات الإعلانية.",
	},
	{
		title: "Block 99",
		slug: "block99",
		type: "التخطيط والتطوير",
		thumbnail: "https://i.ibb.co/Rzdkc6M/thumbnail.jpg",
		slides: [
			"https://i.ibb.co/3zhqJgh/block99-slide-1.jpg",
			"https://i.ibb.co/PFmPZVq/block99-slide-2.jpg",
			"https://i.ibb.co/YTvrwjb/block99-slide-4.jpg",
			"https://i.ibb.co/jwrWLnB/block99-slide-5.jpg",
			"https://i.ibb.co/PQYW1Ws/block99-slide-6.jpg",
			"https://i.ibb.co/vPxvrkz/block99-slide-7.jpg",
			"https://i.ibb.co/Qc6FQXY/block99-slide-9.jpg",
		],
		description: "لقد جددنا قائمتهم وأعدنا تصميم الشعار مع أجواء المدينة.",
	},
	{
		title: "TITO's",
		slug: "tito",
		type: "الدعاية والإعلان",
		thumbnail: "https://i.ibb.co/ZYFzzz8/tito-s-TN.jpg",
		slides: [
			"https://i.ibb.co/vP45L3G/tito-slide-1.jpg",
			"https://i.ibb.co/vQVKVWm/tito-slide-2.jpg",
			"https://i.ibb.co/bXsqQB7/tito-slide-3.jpg",
			"https://i.ibb.co/CVf2LTF/tito-slide-4.jpg",
			"https://i.ibb.co/nfh02rz/tito-slide-5.jpg",
			"https://i.ibb.co/4S6tp75/tito-slide-6.jpg",
			"https://i.ibb.co/W3YSX1K/tito-slide-7.jpg",
			"https://i.ibb.co/xXvxdjn/tito-slide-8.jpg",
			"https://i.ibb.co/8NdbFw7/tito-slide-9.jpg",
			"https://i.ibb.co/K0Lb0r7/tito-slide-10.jpg",
			"https://i.ibb.co/FYmy2n7/tito-slide-11.jpg",
			"https://i.ibb.co/mGTt6nB/tito-slide-12.jpg",
			"https://i.ibb.co/9YLcTdr/tito-slide-13.jpg",
		],
		description: "نقوم بإنشاء تصميم للعلامة التجارية وتصميم رفوف المتجر وتصميم العبوات.",
	},
	{
		title: "Oxi",
		slug: "oxi",
		type: "الدعاية والإعلان",
		thumbnail: "https://i.ibb.co/SrG2HV7/oxi-thumbnail.jpg",
		slides: [
			"https://i.ibb.co/Hq8PDvz/oxi-slide-1.jpg",
			"https://i.ibb.co/8mN7xrt/oxi-slide-2.jpg",
			"https://i.ibb.co/0YZGwKW/oxi-slide-3.jpg",
			"https://i.ibb.co/19JdQQY/oxi-slide-4.jpg",
		],
		description: "لقد قمنا بتغليف مذهل لشرائط التبييض من Oxi white.",
	},
	{
		title: "Dexters",
		slug: "dexters",
		type: "الدعاية والإعلان",
		thumbnail: "https://i.ibb.co/BGQ5YTd/thumbnail.jpg",
		slides: [
			"https://i.ibb.co/pbmwkHY/dexters-slide-1.jpg",
			"https://i.ibb.co/cDZnHQj/dexters-slide-2.jpg",
			"https://i.ibb.co/KqBzSrn/dexters-slide-3.jpg",
			"https://i.ibb.co/pXdj1sW/dexters-slide-4.jpg",
			"https://i.ibb.co/MGqrVtW/dexters-slide-5.jpg",
		],
		description:
			"لقد صممنا الطعام وقمنا بالتقاط الصور لإعادة تصميم قائمتهم ، أثناء إنشاء منشورات على وسائل التواصل الاجتماعي وتصميم اللوحات الإعلانية وحجزها.",
	},
	{
		title: "Rocs",
		slug: "rocs",
		type: "الدعاية والإعلان",
		thumbnail: "https://i.ibb.co/dPmn8TV/THUMBNAIL.jpg",
		slides: [
			"https://i.ibb.co/yFcrKd4/rocs-slide-1.jpg",
			"https://i.ibb.co/P4G3nVm/rocs-slide-2.jpg",
			"https://i.ibb.co/jLH5b7Y/rocs-slide-3.jpg",
			"https://i.ibb.co/r6SJHPq/rocs-slide-4.jpg",
		],
		description: "قمنا بعمل منشورات على وسائل التواصل الاجتماعي وتصميمات داخلية لمتجر R.O.C.S",
	},
	{
		title: "Greens",
		slug: "greens",
		type: "التخطيط والتطوير",
		thumbnail: "https://i.ibb.co/KxQrVvR/greens-thumbnail.jpg",
		slides: [
			"https://i.ibb.co/LRZ13wd/greens-slide-1.jpg",
			"https://i.ibb.co/4Nc2R69/greens-slide-2.jpg",
			"https://i.ibb.co/D4D45Dk/greens-slide-3.jpg",
			"https://i.ibb.co/N2dQx4N/greens-slide-4.jpg",
		],
		description:
			"قمنا ببناء العلامة التجارية لصيدليات جرينز بدءًا من الشعار وتصميم الرول أب وبطاقات العمل أيضًا وحقيبة الهدايا.",
	},
	{
		title: "BME - Beauty Made Easy",
		slug: "beauty-made-easy",
		type: "قسم الابتكار",
		thumbnail: "https://i.ibb.co/mz9bqGJ/bme-thumbnail.jpg",
		slides: [
			"https://i.ibb.co/P9p2Ryk/bme-slide-1.jpg",
			"https://i.ibb.co/R3YGG26/bme-slide-2.jpg",
			"https://i.ibb.co/j6FszPJ/bme-slide-3.jpg",
			"https://i.ibb.co/M2Lj1CL/bme-2.jpg",
			"https://i.ibb.co/P97q2b1/bme.jpg",
		],
		description: "لقد صنعنا تصميمات مبتكرة لرفوف المتجر ، ومنشورات على وسائل التواصل الاجتماعي.",
	},
	{
		title: "Frango",
		slug: "frango",
		type: "الدعاية والإعلان",
		thumbnail: "https://i.ibb.co/tX26y0K/THUMBNAIL.jpg",
		slides: [
			"https://i.ibb.co/Z6SZbRL/frango-slide-1.jpg",
			"https://i.ibb.co/yyFWRMS/frango-slide-2.jpg",
			"https://i.ibb.co/M9MM6Rr/frango-slide-3.jpg",
			"https://i.ibb.co/5TBB7yQ/frango-slide-4.jpg",
			"https://i.ibb.co/RyTzsjj/frango-slide-5.jpg",
		],
		description: "قمنا بتجديد قائمتهم وتصميم القوائم الخاصة بهم.",
	},
	{
		title: "Elite",
		slug: "elite",
		type: "الدعاية والإعلان",
		thumbnail: "https://i.ibb.co/FqfQzQ4/elite-thumbnail.jpg",
		slides: ["https://i.ibb.co/LN6xFmJ/elite-slide-1.jpg"],
		description:
			"نحن قادرون على تخطيط وتطوير علامة تجارية بدءًا من العلامة التجارية / الاستراتيجية الرقمية مروراً باستشارات الأعمال ، واستكمالها من خلال تطوير التطبيقات ، وتطوير الويب المخصص.",
	},
];

export default PROJECTS;
